version: "3.9"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile   
    image: refinedweb-analysis-image 
    container_name: refinedweb-analysis 
    ports:
      - "8888:8888"  # maps container port to localhost
    volumes:
      - .:/app       # mount local folder to /app in container
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    restart: unless-stopped
